--- a/.github/workflows/platform-validation-skip.yml
+++ b/.github/workflows/platform-validation-skip.yml
@@ -20,13 +20,13 @@
 jobs:
   build-android:
     runs-on: ubuntu-latest
-      steps:
-        - run: 'echo "No build required"'
+    steps:
+      - run: 'echo "No build required"'
   build-ios:
     runs-on: ubuntu-latest
-      steps:
-        - run: 'echo "No build required"'
+    steps:
+      - run: 'echo "No build required"'
   check-typescript:
     runs-on: ubuntu-latest
-      steps:
-        - run: 'echo "No build required"'
+    steps:
+      - run: 'echo "No build required"'